# Generated by Django 5.1.1 on 2024-09-15 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='purchase_vendor',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='sale_customer',
        ),
    ]
